spring.application.name=config-server
server.port=8088

# Use native (local file system) for local development
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:/Users/musababdelrahman/Desktop/Dev/GitHub/online-food-ordering-system/config-repo

# Uncomment below for Git-based config (production)
# spring.cloud.config.server.git.uri=https://github.com/mosab9/microservice-config-server
# spring.cloud.config.server.git.default-label=main
